global:
  baseDomain: jumpstarter.10.239.133.131.nip.io
  metrics:
    enabled: false
jumpstarter-controller:
  grpc:
    mode: "ingress"
    nodeport:
      enabled: true
    endpoint: "grpc.jumpstarter.10.239.133.131.nip.io:8082"
    routerEndpoint: "router.jumpstarter.10.239.133.131.nip.io:8083"
  config:
    authentication:
      jwt:
        - issuer:
            url: https://kubernetes.default.svc.cluster.local
            audiences:
              - https://kubernetes.default.svc.cluster.local
            audienceMatchPolicy: MatchAny
            certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          claimMappings:
            username:
              claim: "sub"
              prefix: "kubernetes:"
